version: '3.8'
services:
  cddb_mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=quintor_pw
      - MYSQL_DATABASE=cddb_quintor
      - MYSQL_USER=cddb_quintor
      - MYSQL_PASSWORD=quintor_pw
    ports:
      - 23306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  cddb_frontend:
    build:
      context: frontend
    ports:
      - 20080:80
    # Deprecated but using it since required
    links:
      - 'cddb_backend'
    container_name: cddb_frontend
    image: 'angular-fe:1.0'

  cddb_backend:
    build:
      context: backend
    # Deprecated but using it since required
    links:
      - 'cddb_mysql'
    ports:
      - 28080:8080
    depends_on:
      - cddb_mysql
    container_name: cddb_backend
    image: 'tomcat:8.5-jdk8'
volumes:
  mysql_data: